create table if not exists public."Usuarios" (
    "ID" integer generated by default as identity primary key,
    "Nome" varchar(100) not null,
    "Email" varchar(150) not null,
    "EmailPendente" varchar(150),
    "Senha" text not null,
    "Avatar" varchar(255),
    "Ativo" boolean not null default true,
    "EmailVerificado" boolean not null default false,
    "CodigoVerificacao" varchar(10),
    "CodigoVerificacaoExpiracao" timestamp with time zone,
    "Criado_em" timestamp with time zone not null default now(),
    "DataAtualizacao" timestamp with time zone not null default now()
);

create table if not exists public."Prioridades" (
    "ID" integer generated by default as identity primary key,
    "Nome" varchar(50) not null
);

create table if not exists public."Listas" (
    "ID" integer generated by default as identity primary key,
    "Usuario_id" integer not null,
    "Nome" varchar(100) not null,
    "Cor" varchar(20),
    "Favorita" boolean not null default false,
    "Ordem" integer not null default 0,
    "DataCriacao" timestamp with time zone not null default now(),
    constraint "FK_Listas_Usuarios_Usuario_id"
        foreign key ("Usuario_id")
        references public."Usuarios" ("ID")
        on delete cascade
);

create table if not exists public."Tarefas" (
    "ID" integer generated by default as identity primary key,
    "Lista_id" integer not null,
    "Titulo" varchar(200) not null,
    "Descricao" text,
    "Tags" varchar(255),
    "Prioridade_id" integer,
    "Concluida" boolean not null default false,
    "Arquivada" boolean not null default false,
    "DataVencimento" timestamp with time zone,
    "DataCriacao" timestamp with time zone not null default now(),
    "DataAtualizacao" timestamp with time zone not null default now(),
    "Ordem" integer not null default 0,
    constraint "FK_Tarefas_Listas_Lista_id"
        foreign key ("Lista_id")
        references public."Listas" ("ID")
        on delete cascade,
    constraint "FK_Tarefas_Prioridades_Prioridade_id"
        foreign key ("Prioridade_id")
        references public."Prioridades" ("ID")
        on delete set null
);

create unique index if not exists "IX_Usuarios_Email"
    on public."Usuarios" ("Email");

create index if not exists "IX_Listas_Usuario_id"
    on public."Listas" ("Usuario_id");

create index if not exists "IX_Tarefas_Lista_id"
    on public."Tarefas" ("Lista_id");

create index if not exists "IX_Tarefas_Prioridade_id"
    on public."Tarefas" ("Prioridade_id");
